version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ava
    versions:
    - "> 3.5.0"
    - "< 4"
  - dependency-name: p-event
    versions:
    - "> 4.1.0"
    - "< 5"
  - dependency-name: semantic-release
    versions:
    - "> 17.0.4"
    - "< 18"
  - dependency-name: xo
    versions:
    - "> 0.28.0"
    - "< 1"
